"""Regenerate data/sp500.js: monthly S&P composite (Shiller, extended with FRED) since 1871.

Source: https://github.com/datasets/s-and-p-500 (data/data.csv), a tidied copy of
Robert Shiller's monthly series (monthly averages of daily closes), extended with FRED.
Usage: python3 scripts/fetch_sp500.py
"""
import csv
import io
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/datasets/s-and-p-500/main/data/data.csv"
OUT = Path(__file__).resolve().parent.parent / "data/sp500.js"


def main():
    raw = urllib.request.urlopen(URL, timeout=60).read().decode("utf-8")
    rows = [(r["Date"][:7], float(r["SP500"])) for r in csv.DictReader(io.StringIO(raw)) if r["SP500"]]
    rows.sort()
    start = rows[0][0]
    # Stored as one value per month from `start`, to keep the file small.
    values = ",".join(f"{v:g}" for _, v in rows)
    OUT.write_text(
        "// Generated by scripts/fetch_sp500.py. Monthly S&P composite (Shiller; FRED after 2023-06).\n"
        "// Monthly averages of daily closes, so single-day crashes look smaller than they were.\n"
        f'window.SP500_MONTHLY = {{ start: "{start}", source: "{URL}", values: [{values}] }};\n',
        encoding="utf-8",
    )
    print(f"Wrote {len(rows)} months from {start} to {rows[-1][0]}")


if __name__ == "__main__":
    main()
