"""Regenerate data/events.js from the source spreadsheet.

Usage: python3 scripts/import_events.py [path/to/workbook.xlsx]
Requires openpyxl.
"""
import json
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = ROOT / "data/source/Financial_Crises_Bubbles_and_Scandals_0800_2026.xlsx"

COLUMNS = ["year", "era", "status", "title", "category", "geography", "summary", "severity"]


def clean(value):
    if isinstance(value, str):
        value = value.strip()
        return "" if value in ("-", "None") else value
    return value


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    wb = openpyxl.load_workbook(src, read_only=True)
    ws = wb["Year by Year"]
    header = [c for c in next(ws.iter_rows(min_row=1, max_row=1, values_only=True))]
    assert header[0] == "Year" and header[7].startswith("Severity"), header

    events = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0] is None:
            continue
        rec = dict(zip(COLUMNS, row))
        rec["year"] = int(rec["year"])
        rec["severity"] = int(rec["severity"] or 0)
        rec["status"] = "event" if str(rec["status"]).upper() == "EVENT" else "quiet"
        for key in ("era", "title", "category", "geography", "summary"):
            rec[key] = clean(rec[key]) or ""
        events.append(rec)

    events.sort(key=lambda e: e["year"])
    payload = json.dumps(events, ensure_ascii=False, indent=1)
    (ROOT / "data/events.js").write_text(
        "// Generated by scripts/import_events.py from the source workbook. Do not edit by hand.\n"
        f"window.CRISIS_EVENTS = {payload};\n",
        encoding="utf-8",
    )
    n_events = sum(e["status"] == "event" for e in events)
    print(f"Wrote {len(events)} years ({n_events} event years) from {src.name}")


if __name__ == "__main__":
    main()
